import json
from datetime import datetime, timedelta

from werkzeug.security import generate_password_hash

from models import db, Incident, Relief, SOS, Shelter, User


def ensure_demo_user():
    user = User.query.filter_by(username="dashboard.demo@example.com").first()
    if user:
        return user

    user = User(
        username="dashboard.demo@example.com",
        password=generate_password_hash("admin123"),
        role="admin",
    )
    db.session.add(user)
    db.session.flush()
    return user


def ensure_sample_data():
    demo_user = ensure_demo_user()
    now = datetime.utcnow()

    incidents = [
        {
            "title": "Flash Flood Near Pari Chowk",
            "description": "Heavy rain has flooded the underpass and traffic movement is blocked.",
            "city": "Greater Noida",
            "priority": "high",
            "status": "reported",
            "latitude": 28.4744,
            "longitude": 77.5030,
            "created_at": now - timedelta(minutes=35),
            "updated_at": now - timedelta(minutes=35),
        },
        {
            "title": "Residential Fire in Sector 62",
            "description": "Fire brigade requested for smoke coming from a residential building.",
            "city": "Noida",
            "priority": "high",
            "status": "verified",
            "latitude": 28.6289,
            "longitude": 77.3649,
            "created_at": now - timedelta(hours=1, minutes=10),
            "updated_at": now - timedelta(minutes=55),
        },
        {
            "title": "Road Cave-In at Indirapuram Link Road",
            "description": "A portion of the service road has collapsed after overnight rain.",
            "city": "Ghaziabad",
            "priority": "medium",
            "status": "reported",
            "latitude": 28.6383,
            "longitude": 77.3700,
            "created_at": now - timedelta(hours=2, minutes=20),
            "updated_at": now - timedelta(hours=2, minutes=20),
        },
        {
            "title": "Power Outage at NIT Faridabad Block",
            "description": "Emergency crews needed after transformer failure during storm conditions.",
            "city": "Faridabad",
            "priority": "medium",
            "status": "resolved",
            "latitude": 28.4089,
            "longitude": 77.3178,
            "created_at": now - timedelta(hours=5),
            "updated_at": now - timedelta(hours=3, minutes=30),
        },
        {
            "title": "Riverbank Erosion Reported in Yamuna Khadar",
            "description": "Residents report rapid erosion close to temporary homes along the floodplain.",
            "city": "Delhi",
            "priority": "high",
            "status": "verified",
            "latitude": 28.6094,
            "longitude": 77.2523,
            "created_at": now - timedelta(hours=1, minutes=45),
            "updated_at": now - timedelta(hours=1, minutes=5),
        },
        {
            "title": "Waterlogging Near Gurugram Bus Stand",
            "description": "Commuters are stranded and buses are being rerouted due to deep waterlogging.",
            "city": "Gurugram",
            "priority": "medium",
            "status": "reported",
            "latitude": 28.4591,
            "longitude": 77.0266,
            "created_at": now - timedelta(hours=2, minutes=10),
            "updated_at": now - timedelta(hours=2, minutes=10),
        },
        {
            "title": "Landslide Debris on Shimla Bypass",
            "description": "Road partially blocked after hillside debris slipped onto the bypass.",
            "city": "Shimla",
            "priority": "high",
            "status": "reported",
            "latitude": 31.1048,
            "longitude": 77.1734,
            "created_at": now - timedelta(hours=6, minutes=40),
            "updated_at": now - timedelta(hours=6, minutes=20),
        },
        {
            "title": "Storm Damage Near Chandigarh Sector 17",
            "description": "Trees and electric poles damaged after strong winds in the market district.",
            "city": "Chandigarh",
            "priority": "medium",
            "status": "verified",
            "latitude": 30.7415,
            "longitude": 76.7681,
            "created_at": now - timedelta(hours=7, minutes=15),
            "updated_at": now - timedelta(hours=6, minutes=55),
        },
    ]

    incidents.extend([
        {
            "title": "Coastal Flooding at Visakhapatnam Fishing Harbor",
            "description": "High tide and strong winds have inundated access roads near the harbor.",
            "city": "Visakhapatnam, Andhra Pradesh",
            "priority": "high",
            "status": "reported",
            "latitude": 17.6868,
            "longitude": 83.2185,
            "created_at": now - timedelta(hours=3, minutes=10),
            "updated_at": now - timedelta(hours=2, minutes=40),
        },
        {
            "title": "Hill Road Blocked Near Itanagar Market",
            "description": "Loose debris has blocked a key approach road after overnight rain.",
            "city": "Itanagar, Arunachal Pradesh",
            "priority": "medium",
            "status": "reported",
            "latitude": 27.0844,
            "longitude": 93.6053,
            "created_at": now - timedelta(hours=8, minutes=5),
            "updated_at": now - timedelta(hours=7, minutes=35),
        },
        {
            "title": "Brahmaputra Water Rise at Guwahati Riverside",
            "description": "Water levels are nearing warning marks and low-lying homes are affected.",
            "city": "Guwahati, Assam",
            "priority": "high",
            "status": "verified",
            "latitude": 26.1445,
            "longitude": 91.7362,
            "created_at": now - timedelta(hours=4, minutes=25),
            "updated_at": now - timedelta(hours=3, minutes=55),
        },
        {
            "title": "Embankment Breach Alert in Patna Diara Belt",
            "description": "Local volunteers report seepage and partial embankment failure near settlements.",
            "city": "Patna, Bihar",
            "priority": "high",
            "status": "reported",
            "latitude": 25.5941,
            "longitude": 85.1376,
            "created_at": now - timedelta(hours=5, minutes=30),
            "updated_at": now - timedelta(hours=4, minutes=50),
        },
        {
            "title": "Bridge Approach Erosion Near Raipur Bypass",
            "description": "Fast-moving runoff has eroded the shoulder close to a major crossing.",
            "city": "Raipur, Chhattisgarh",
            "priority": "medium",
            "status": "verified",
            "latitude": 21.2514,
            "longitude": 81.6296,
            "created_at": now - timedelta(hours=6, minutes=5),
            "updated_at": now - timedelta(hours=5, minutes=20),
        },
        {
            "title": "Tidal Surge at Panaji Riverfront",
            "description": "Shops along the promenade report water ingress and utility disruption.",
            "city": "Panaji, Goa",
            "priority": "medium",
            "status": "reported",
            "latitude": 15.4909,
            "longitude": 73.8278,
            "created_at": now - timedelta(hours=2, minutes=55),
            "updated_at": now - timedelta(hours=2, minutes=15),
        },
        {
            "title": "Industrial Fire Near Ahmedabad Naroda Zone",
            "description": "A warehouse fire has triggered evacuation of nearby workers.",
            "city": "Ahmedabad, Gujarat",
            "priority": "high",
            "status": "verified",
            "latitude": 23.0225,
            "longitude": 72.5714,
            "created_at": now - timedelta(hours=1, minutes=40),
            "updated_at": now - timedelta(hours=1, minutes=5),
        },
        {
            "title": "Water Scarcity Protest Escalation in Ranchi Outskirts",
            "description": "Emergency tankers requested after borewell failures in multiple settlements.",
            "city": "Ranchi, Jharkhand",
            "priority": "medium",
            "status": "reported",
            "latitude": 23.3441,
            "longitude": 85.3096,
            "created_at": now - timedelta(hours=9, minutes=10),
            "updated_at": now - timedelta(hours=8, minutes=30),
        },
        {
            "title": "Urban Flooding in Bengaluru Silk Board Junction",
            "description": "Vehicles stalled and drainage overflow reported during intense rainfall.",
            "city": "Bengaluru, Karnataka",
            "priority": "high",
            "status": "reported",
            "latitude": 12.9172,
            "longitude": 77.6220,
            "created_at": now - timedelta(hours=2, minutes=30),
            "updated_at": now - timedelta(hours=2, minutes=10),
        },
        {
            "title": "Landslip Reported Near Kochi Hill Cut Road",
            "description": "A small landslip has blocked one lane and threatens nearby houses.",
            "city": "Kochi, Kerala",
            "priority": "medium",
            "status": "verified",
            "latitude": 9.9312,
            "longitude": 76.2673,
            "created_at": now - timedelta(hours=7, minutes=5),
            "updated_at": now - timedelta(hours=6, minutes=30),
        },
        {
            "title": "Dam Spillway Warning for Bhopal Suburbs",
            "description": "Authorities issued alerts for controlled release affecting low-lying areas.",
            "city": "Bhopal, Madhya Pradesh",
            "priority": "high",
            "status": "reported",
            "latitude": 23.2599,
            "longitude": 77.4126,
            "created_at": now - timedelta(hours=5, minutes=55),
            "updated_at": now - timedelta(hours=5, minutes=10),
        },
        {
            "title": "Building Crack Complaint in Mumbai Kurla Belt",
            "description": "Residents were evacuated after visible structural cracks widened overnight.",
            "city": "Mumbai, Maharashtra",
            "priority": "high",
            "status": "verified",
            "latitude": 19.0760,
            "longitude": 72.8777,
            "created_at": now - timedelta(hours=3, minutes=45),
            "updated_at": now - timedelta(hours=3, minutes=5),
        },
        {
            "title": "Flash Flood Stream Crossing in Imphal East",
            "description": "Water from nearby drains has cut off access to two neighborhoods.",
            "city": "Imphal, Manipur",
            "priority": "medium",
            "status": "reported",
            "latitude": 24.8170,
            "longitude": 93.9368,
            "created_at": now - timedelta(hours=10, minutes=25),
            "updated_at": now - timedelta(hours=9, minutes=50),
        },
        {
            "title": "Slope Failure Near Shillong Upper Ridge",
            "description": "Retaining wall fragments have fallen onto a residential lane.",
            "city": "Shillong, Meghalaya",
            "priority": "medium",
            "status": "verified",
            "latitude": 25.5788,
            "longitude": 91.8933,
            "created_at": now - timedelta(hours=8, minutes=20),
            "updated_at": now - timedelta(hours=7, minutes=45),
        },
        {
            "title": "Road Washout on Aizawl Peripheral Route",
            "description": "A culvert overflow has damaged the edge of the hillside road.",
            "city": "Aizawl, Mizoram",
            "priority": "high",
            "status": "reported",
            "latitude": 23.7271,
            "longitude": 92.7176,
            "created_at": now - timedelta(hours=11, minutes=15),
            "updated_at": now - timedelta(hours=10, minutes=40),
        },
        {
            "title": "Power Line Collapse Near Kohima Town",
            "description": "Emergency teams are clearing snapped lines after a windstorm.",
            "city": "Kohima, Nagaland",
            "priority": "medium",
            "status": "resolved",
            "latitude": 25.6751,
            "longitude": 94.1086,
            "created_at": now - timedelta(hours=12, minutes=5),
            "updated_at": now - timedelta(hours=9, minutes=30),
        },
        {
            "title": "Cyclone Damage in Puri Beachfront Colony",
            "description": "Temporary shelters and kiosks suffered major damage from coastal winds.",
            "city": "Puri, Odisha",
            "priority": "high",
            "status": "verified",
            "latitude": 19.8135,
            "longitude": 85.8312,
            "created_at": now - timedelta(hours=4, minutes=50),
            "updated_at": now - timedelta(hours=4, minutes=5),
        },
        {
            "title": "Canal Overflow in Ludhiana Industrial Belt",
            "description": "Factory access roads are flooded and workers are stranded inside units.",
            "city": "Ludhiana, Punjab",
            "priority": "high",
            "status": "reported",
            "latitude": 30.9009,
            "longitude": 75.8573,
            "created_at": now - timedelta(hours=6, minutes=45),
            "updated_at": now - timedelta(hours=6, minutes=10),
        },
        {
            "title": "Heatwave Emergency at Jaipur Bus Terminal",
            "description": "Several commuters collapsed due to severe heat stress and dehydration.",
            "city": "Jaipur, Rajasthan",
            "priority": "high",
            "status": "verified",
            "latitude": 26.9124,
            "longitude": 75.7873,
            "created_at": now - timedelta(hours=1, minutes=55),
            "updated_at": now - timedelta(hours=1, minutes=15),
        },
        {
            "title": "Rockfall Alert Near Gangtok Ridge Road",
            "description": "Falling stones have blocked uphill movement toward residential clusters.",
            "city": "Gangtok, Sikkim",
            "priority": "medium",
            "status": "reported",
            "latitude": 27.3389,
            "longitude": 88.6065,
            "created_at": now - timedelta(hours=9, minutes=35),
            "updated_at": now - timedelta(hours=9),
        },
        {
            "title": "Chennai Stormwater Drain Overflow in Velachery",
            "description": "Water entered ground-floor homes after drainage pumps failed.",
            "city": "Chennai, Tamil Nadu",
            "priority": "high",
            "status": "reported",
            "latitude": 12.9716,
            "longitude": 80.2212,
            "created_at": now - timedelta(hours=2, minutes=20),
            "updated_at": now - timedelta(hours=1, minutes=50),
        },
        {
            "title": "Lake Bund Seepage Near Hyderabad Outer Ring",
            "description": "Civic workers placed barricades after seepage was spotted near a bund wall.",
            "city": "Hyderabad, Telangana",
            "priority": "medium",
            "status": "verified",
            "latitude": 17.3850,
            "longitude": 78.4867,
            "created_at": now - timedelta(hours=4, minutes=15),
            "updated_at": now - timedelta(hours=3, minutes=45),
        },
        {
            "title": "Bridge Deck Damage at Agartala Connector",
            "description": "A damaged expansion joint has slowed traffic and raised safety concerns.",
            "city": "Agartala, Tripura",
            "priority": "medium",
            "status": "reported",
            "latitude": 23.8315,
            "longitude": 91.2868,
            "created_at": now - timedelta(hours=10, minutes=5),
            "updated_at": now - timedelta(hours=9, minutes=25),
        },
        {
            "title": "Cloudburst Runoff in Dehradun Canal Road",
            "description": "Sudden runoff carried debris into homes and blocked local traffic.",
            "city": "Dehradun, Uttarakhand",
            "priority": "high",
            "status": "verified",
            "latitude": 30.3165,
            "longitude": 78.0322,
            "created_at": now - timedelta(hours=5, minutes=15),
            "updated_at": now - timedelta(hours=4, minutes=35),
        },
        {
            "title": "Embankment Overtopping at Kolkata Riverside Ward",
            "description": "Residents are moving belongings after water spilled over a protective embankment.",
            "city": "Kolkata, West Bengal",
            "priority": "high",
            "status": "reported",
            "latitude": 22.5726,
            "longitude": 88.3639,
            "created_at": now - timedelta(hours=3, minutes=25),
            "updated_at": now - timedelta(hours=2, minutes=55),
        },
        {
            "title": "Snow Clearance Delay on Srinagar Airport Road",
            "description": "Heavy snowfall is slowing emergency movement toward the airport corridor.",
            "city": "Srinagar, Jammu and Kashmir",
            "priority": "medium",
            "status": "resolved",
            "latitude": 34.0837,
            "longitude": 74.7973,
            "created_at": now - timedelta(hours=13, minutes=15),
            "updated_at": now - timedelta(hours=11, minutes=40),
        },
        {
            "title": "Avalanche Warning Near Leh Access Route",
            "description": "Convoys are being halted after fresh avalanche deposits were observed roadside.",
            "city": "Leh, Ladakh",
            "priority": "high",
            "status": "reported",
            "latitude": 34.1526,
            "longitude": 77.5770,
            "created_at": now - timedelta(hours=14, minutes=20),
            "updated_at": now - timedelta(hours=13, minutes=50),
        },
        {
            "title": "Seawater Intrusion in Puducherry Beach Road",
            "description": "Waves breached barriers and flooded parking and kiosks on the promenade.",
            "city": "Puducherry",
            "priority": "medium",
            "status": "reported",
            "latitude": 11.9416,
            "longitude": 79.8083,
            "created_at": now - timedelta(hours=4, minutes=5),
            "updated_at": now - timedelta(hours=3, minutes=20),
        },
        {
            "title": "Jetty Damage on Port Blair Waterfront",
            "description": "Storm surge caused partial damage to boarding structures and waiting sheds.",
            "city": "Port Blair, Andaman and Nicobar Islands",
            "priority": "high",
            "status": "verified",
            "latitude": 11.6234,
            "longitude": 92.7265,
            "created_at": now - timedelta(hours=15, minutes=5),
            "updated_at": now - timedelta(hours=14, minutes=30),
        },
        {
            "title": "Lagoon Flooding Near Kavaratti Settlement",
            "description": "Wave action and heavy rain flooded low-lying homes near the lagoon edge.",
            "city": "Kavaratti, Lakshadweep",
            "priority": "high",
            "status": "reported",
            "latitude": 10.5667,
            "longitude": 72.6417,
            "created_at": now - timedelta(hours=16, minutes=10),
            "updated_at": now - timedelta(hours=15, minutes=35),
        },
        {
            "title": "Hazardous Foam Spill on Mangaluru Drain Channel",
            "description": "Residents reported chemical foam overflow after industrial discharge mixed with rainwater.",
            "city": "Mangaluru, Karnataka",
            "priority": "medium",
            "status": "reported",
            "latitude": 12.9141,
            "longitude": 74.8560,
            "created_at": now - timedelta(hours=6, minutes=25),
            "updated_at": now - timedelta(hours=5, minutes=55),
        },
        {
            "title": "Damaged Roof Collapse in Nashik Old City",
            "description": "Part of a weakened roof collapsed in a market lane after continuous rainfall.",
            "city": "Nashik, Maharashtra",
            "priority": "high",
            "status": "verified",
            "latitude": 19.9975,
            "longitude": 73.7898,
            "created_at": now - timedelta(hours=7, minutes=45),
            "updated_at": now - timedelta(hours=7, minutes=5),
        },
        {
            "title": "Waterlogging at Surat Textile Cluster",
            "description": "Flooded internal roads are preventing workers from leaving the cluster safely.",
            "city": "Surat, Gujarat",
            "priority": "medium",
            "status": "reported",
            "latitude": 21.1702,
            "longitude": 72.8311,
            "created_at": now - timedelta(hours=3, minutes=5),
            "updated_at": now - timedelta(hours=2, minutes=25),
        },
        {
            "title": "Railway Underpass Flooded in Bhubaneswar",
            "description": "Emergency pumping has been requested as commuters remain stranded.",
            "city": "Bhubaneswar, Odisha",
            "priority": "medium",
            "status": "verified",
            "latitude": 20.2961,
            "longitude": 85.8245,
            "created_at": now - timedelta(hours=2, minutes=45),
            "updated_at": now - timedelta(hours=2, minutes=5),
        },
        {
            "title": "Temple Town Crowd Crush Risk in Madurai",
            "description": "Police requested medical backup after overcrowding built near a festival route.",
            "city": "Madurai, Tamil Nadu",
            "priority": "high",
            "status": "reported",
            "latitude": 9.9252,
            "longitude": 78.1198,
            "created_at": now - timedelta(hours=1, minutes=25),
            "updated_at": now - timedelta(minutes=55),
        },
        {
            "title": "Street Cave-In Near Lucknow Gomti Embankment",
            "description": "A road section caved in after leakage from an underground utility line.",
            "city": "Lucknow, Uttar Pradesh",
            "priority": "high",
            "status": "verified",
            "latitude": 26.8467,
            "longitude": 80.9462,
            "created_at": now - timedelta(hours=4, minutes=35),
            "updated_at": now - timedelta(hours=3, minutes=50),
        },
        {
            "title": "Drain Backflow in Varanasi Riverfront Lanes",
            "description": "Backflow from storm drains entered multiple homes near the ghat road.",
            "city": "Varanasi, Uttar Pradesh",
            "priority": "medium",
            "status": "reported",
            "latitude": 25.3176,
            "longitude": 82.9739,
            "created_at": now - timedelta(hours=5, minutes=5),
            "updated_at": now - timedelta(hours=4, minutes=20),
        },
        {
            "title": "Bus Depot Fire Scare in Thiruvananthapuram",
            "description": "Smoke from an electrical panel forced temporary evacuation of the depot.",
            "city": "Thiruvananthapuram, Kerala",
            "priority": "medium",
            "status": "resolved",
            "latitude": 8.5241,
            "longitude": 76.9366,
            "created_at": now - timedelta(hours=9, minutes=45),
            "updated_at": now - timedelta(hours=8, minutes=10),
        },
        {
            "title": "Landslide Threat Near Dharamshala Bypass",
            "description": "Heavy mountain runoff loosened boulders above a residential road segment.",
            "city": "Dharamshala, Himachal Pradesh",
            "priority": "high",
            "status": "reported",
            "latitude": 32.2190,
            "longitude": 76.3234,
            "created_at": now - timedelta(hours=7, minutes=20),
            "updated_at": now - timedelta(hours=6, minutes=35),
        },
        {
            "title": "Market Area Flooding in Siliguri Junction",
            "description": "Persistent rainwater accumulation has cut access to shops and schools.",
            "city": "Siliguri, West Bengal",
            "priority": "medium",
            "status": "reported",
            "latitude": 26.7271,
            "longitude": 88.3953,
            "created_at": now - timedelta(hours=6, minutes=55),
            "updated_at": now - timedelta(hours=6, minutes=5),
        },
        {
            "title": "Coal Belt Subsidence Alert in Dhanbad",
            "description": "Ground subsidence cracks were reported near a dense worker settlement.",
            "city": "Dhanbad, Jharkhand",
            "priority": "high",
            "status": "verified",
            "latitude": 23.7957,
            "longitude": 86.4304,
            "created_at": now - timedelta(hours=8, minutes=45),
            "updated_at": now - timedelta(hours=7, minutes=55),
        },
        {
            "title": "Urban Fire Outbreak in Cuttack Warehouse Strip",
            "description": "A row of storage units caught fire, prompting area-wide evacuation.",
            "city": "Cuttack, Odisha",
            "priority": "high",
            "status": "verified",
            "latitude": 20.4625,
            "longitude": 85.8828,
            "created_at": now - timedelta(hours=2, minutes=5),
            "updated_at": now - timedelta(hours=1, minutes=35),
        },
        {
            "title": "Low-Lying Colony Flooded in Vijayawada",
            "description": "Pumping assistance requested after water entered dozens of homes.",
            "city": "Vijayawada, Andhra Pradesh",
            "priority": "high",
            "status": "reported",
            "latitude": 16.5062,
            "longitude": 80.6480,
            "created_at": now - timedelta(hours=4, minutes=55),
            "updated_at": now - timedelta(hours=4, minutes=15),
        },
        {
            "title": "Festival Crowd Emergency in Amritsar Heritage Zone",
            "description": "Medical teams requested after crowd congestion caused multiple fainting cases.",
            "city": "Amritsar, Punjab",
            "priority": "medium",
            "status": "reported",
            "latitude": 31.6340,
            "longitude": 74.8723,
            "created_at": now - timedelta(hours=3, minutes=35),
            "updated_at": now - timedelta(hours=2, minutes=50),
        },
        {
            "title": "Flash Flood Warning Near Udaipur Lake Edge",
            "description": "Rapid inflow into lake channels threatens roadside stalls and vehicles.",
            "city": "Udaipur, Rajasthan",
            "priority": "medium",
            "status": "reported",
            "latitude": 24.5854,
            "longitude": 73.7125,
            "created_at": now - timedelta(hours=5, minutes=40),
            "updated_at": now - timedelta(hours=5),
        },
        {
            "title": "Monsoon Treefall Across Bhopal Link Road",
            "description": "A fallen tree is blocking ambulance movement in a busy corridor.",
            "city": "Bhopal, Madhya Pradesh",
            "priority": "medium",
            "status": "resolved",
            "latitude": 23.2336,
            "longitude": 77.4331,
            "created_at": now - timedelta(hours=8, minutes=55),
            "updated_at": now - timedelta(hours=7, minutes=20),
        },
    ])

    shelters = [
        {
            "name": "Greater Noida Community Hall Shelter",
            "city": "Greater Noida",
            "address": "Pari Chowk Civic Center, Greater Noida",
            "latitude": 28.4734,
            "longitude": 77.5040,
            "capacity": 220,
            "occupied": 86,
            "contact": "+91 9876500101",
            "facilities": ["Medical Aid", "Food", "Water", "Bedding"],
            "status": "active",
        },
        {
            "name": "Noida Sector 62 School Shelter",
            "city": "Noida",
            "address": "Government Senior Secondary School, Sector 62, Noida",
            "latitude": 28.6280,
            "longitude": 77.3642,
            "capacity": 180,
            "occupied": 124,
            "contact": "+91 9876500102",
            "facilities": ["Food", "Water", "Bedding"],
            "status": "active",
        },
        {
            "name": "Ghaziabad Sports Complex Shelter",
            "city": "Ghaziabad",
            "address": "District Sports Complex, Indirapuram, Ghaziabad",
            "latitude": 28.6421,
            "longitude": 77.3693,
            "capacity": 260,
            "occupied": 91,
            "contact": "+91 9876500103",
            "facilities": ["Medical Aid", "Water", "Bedding"],
            "status": "active",
        },
        {
            "name": "Faridabad Transit Relief Shelter",
            "city": "Faridabad",
            "address": "Old Town Community Center, Faridabad",
            "latitude": 28.4080,
            "longitude": 77.3101,
            "capacity": 150,
            "occupied": 58,
            "contact": "+91 9876500104",
            "facilities": ["Food", "Water"],
            "status": "active",
        },
        {
            "name": "Kalindi Kunj Riverside Shelter",
            "city": "Delhi",
            "address": "Riverside Relief Camp, Kalindi Kunj, Delhi",
            "latitude": 28.5438,
            "longitude": 77.3076,
            "capacity": 210,
            "occupied": 132,
            "contact": "+91 9876500105",
            "facilities": ["Medical Aid", "Food", "Water", "Child Support"],
            "status": "active",
        },
        {
            "name": "Gurugram Civic Center Shelter",
            "city": "Gurugram",
            "address": "Mini Secretariat Hall, Gurugram",
            "latitude": 28.4605,
            "longitude": 77.0288,
            "capacity": 175,
            "occupied": 69,
            "contact": "+91 9876500106",
            "facilities": ["Food", "Water", "Bedding", "Charging Points"],
            "status": "active",
        },
        {
            "name": "Shimla District Hall Shelter",
            "city": "Shimla",
            "address": "District Hall, Shimla",
            "latitude": 31.1034,
            "longitude": 77.1752,
            "capacity": 140,
            "occupied": 74,
            "contact": "+91 9876500107",
            "facilities": ["Medical Aid", "Bedding", "Warm Clothing"],
            "status": "active",
        },
        {
            "name": "Chandigarh Community Arena Shelter",
            "city": "Chandigarh",
            "address": "Sector 17 Community Arena, Chandigarh",
            "latitude": 30.7395,
            "longitude": 76.7730,
            "capacity": 190,
            "occupied": 83,
            "contact": "+91 9876500108",
            "facilities": ["Food", "Water", "Counselling", "Medical Aid"],
            "status": "active",
        },
    ]

    relief_centers = [
        {
            "name": "Botanical Garden Medical Center",
            "type": "Medical Center",
            "city": "Noida",
            "address": "Near Botanical Garden Metro Station, Noida",
            "contact": "+91 9811002201",
            "latitude": 28.5642,
            "longitude": 77.3343,
            "supplies": ["Medicine", "Water", "Blankets", "First Aid Kits"],
            "status": "operational",
            "created_at": now - timedelta(minutes=50),
            "updated_at": now - timedelta(minutes=50),
        },
        {
            "name": "Pari Chowk Food Distribution Center",
            "type": "Food Distribution",
            "city": "Greater Noida",
            "address": "Expo Plaza Service Lane, Greater Noida",
            "contact": "+91 9811002202",
            "latitude": 28.4718,
            "longitude": 77.5038,
            "supplies": ["Food", "Water", "Baby Food"],
            "status": "operational",
            "created_at": now - timedelta(hours=1, minutes=30),
            "updated_at": now - timedelta(hours=1, minutes=5),
        },
        {
            "name": "Indirapuram Emergency Supply Hub",
            "type": "Supply Center",
            "city": "Ghaziabad",
            "address": "Kala Pathar Road, Indirapuram, Ghaziabad",
            "contact": "+91 9811002203",
            "latitude": 28.6405,
            "longitude": 77.3695,
            "supplies": ["Water", "Food", "Clothing", "Tools", "Blankets"],
            "status": "operational",
            "created_at": now - timedelta(hours=3),
            "updated_at": now - timedelta(hours=2, minutes=40),
        },
        {
            "name": "Okhla Border Aid Station",
            "type": "Aid Station",
            "city": "Delhi",
            "address": "Kalindi Kunj Road, Delhi",
            "contact": "+91 9811002204",
            "latitude": 28.5450,
            "longitude": 77.3051,
            "supplies": ["Medicine", "Food", "Water"],
            "status": "operational",
            "created_at": now - timedelta(hours=4, minutes=10),
            "updated_at": now - timedelta(hours=4),
        },
        {
            "name": "Gurugram Rapid Response Depot",
            "type": "Supply Center",
            "city": "Gurugram",
            "address": "Rajiv Chowk Service Road, Gurugram",
            "contact": "+91 9811002205",
            "latitude": 28.4598,
            "longitude": 77.0325,
            "supplies": ["Water", "Blankets", "Hygiene Kits", "Tarpaulins"],
            "status": "operational",
            "created_at": now - timedelta(hours=2, minutes=10),
            "updated_at": now - timedelta(hours=1, minutes=45),
        },
        {
            "name": "Shimla Mountain Aid Base",
            "type": "Medical Center",
            "city": "Shimla",
            "address": "Cart Road Relief Post, Shimla",
            "contact": "+91 9811002206",
            "latitude": 31.1055,
            "longitude": 77.1707,
            "supplies": ["Medicine", "First Aid Kits", "Blankets", "Hot Meals"],
            "status": "operational",
            "created_at": now - timedelta(hours=6),
            "updated_at": now - timedelta(hours=5, minutes=25),
        },
        {
            "name": "Chandigarh Emergency Resource Hub",
            "type": "Aid Station",
            "city": "Chandigarh",
            "address": "Sector 22 Relief Coordination Point, Chandigarh",
            "contact": "+91 9811002207",
            "latitude": 30.7337,
            "longitude": 76.7794,
            "supplies": ["Food", "Water", "Medicine", "Power Banks"],
            "status": "operational",
            "created_at": now - timedelta(hours=7, minutes=30),
            "updated_at": now - timedelta(hours=7),
        },
        {
            "name": "Faridabad Mobile Health Camp",
            "type": "Medical Center",
            "city": "Faridabad",
            "address": "NIT Central Park, Faridabad",
            "contact": "+91 9811002208",
            "latitude": 28.4110,
            "longitude": 77.3148,
            "supplies": ["Medicine", "ORS", "First Aid Kits", "Baby Care"],
            "status": "operational",
            "created_at": now - timedelta(hours=3, minutes=20),
            "updated_at": now - timedelta(hours=2, minutes=55),
        },
    ]

    sos_entries = [
        {
            "message": "Need insulin and medical support for an elderly person in Sector 18.",
            "phone": "+91 9899003301",
            "city": "Noida",
            "priority": "high",
            "status": "new",
            "latitude": 28.5708,
            "longitude": 77.3260,
            "created_at": now - timedelta(minutes=18),
            "updated_at": now - timedelta(minutes=18),
        },
        {
            "message": "Two children stranded near a flooded lane close to Pari Chowk.",
            "phone": "+91 9899003302",
            "city": "Greater Noida",
            "priority": "high",
            "status": "acknowledged",
            "latitude": 28.4728,
            "longitude": 77.5053,
            "created_at": now - timedelta(minutes=42),
            "updated_at": now - timedelta(minutes=20),
        },
        {
            "message": "Family requesting dry food packets and blankets near Indirapuram.",
            "phone": "+91 9899003303",
            "city": "Ghaziabad",
            "priority": "medium",
            "status": "new",
            "latitude": 28.6368,
            "longitude": 77.3688,
            "created_at": now - timedelta(hours=1, minutes=25),
            "updated_at": now - timedelta(hours=1, minutes=25),
        },
        {
            "message": "Evacuation assistance needed for a disabled resident in Faridabad.",
            "phone": "+91 9899003304",
            "city": "Faridabad",
            "priority": "medium",
            "status": "handled",
            "latitude": 28.4095,
            "longitude": 77.3140,
            "created_at": now - timedelta(hours=6),
            "updated_at": now - timedelta(hours=5, minutes=15),
        },
        {
            "message": "Need drinking water and baby formula near Kalindi Kunj relief line.",
            "phone": "+91 9899003305",
            "city": "Delhi",
            "priority": "high",
            "status": "acknowledged",
            "latitude": 28.5442,
            "longitude": 77.3064,
            "created_at": now - timedelta(minutes=58),
            "updated_at": now - timedelta(minutes=26),
        },
        {
            "message": "Senior citizens trapped on first floor due to road flooding in Gurugram.",
            "phone": "+91 9899003306",
            "city": "Gurugram",
            "priority": "high",
            "status": "new",
            "latitude": 28.4577,
            "longitude": 77.0309,
            "created_at": now - timedelta(hours=2, minutes=5),
            "updated_at": now - timedelta(hours=2, minutes=5),
        },
        {
            "message": "Urgent requirement for blankets and medical support near Shimla bypass.",
            "phone": "+91 9899003307",
            "city": "Shimla",
            "priority": "medium",
            "status": "new",
            "latitude": 31.1028,
            "longitude": 77.1718,
            "created_at": now - timedelta(hours=5, minutes=35),
            "updated_at": now - timedelta(hours=5, minutes=35),
        },
        {
            "message": "Requesting assistance to clear fallen tree blocking residential lane in Chandigarh.",
            "phone": "+91 9899003308",
            "city": "Chandigarh",
            "priority": "medium",
            "status": "handled",
            "latitude": 30.7427,
            "longitude": 76.7705,
            "created_at": now - timedelta(hours=7, minutes=50),
            "updated_at": now - timedelta(hours=6, minutes=45),
        },
    ]

    sos_entries.extend([
        {
            "message": "Need rescue boat support for families stranded near Guwahati riverbank homes.",
            "phone": "+91 9899003309",
            "city": "Guwahati, Assam",
            "priority": "high",
            "status": "new",
            "latitude": 26.1492,
            "longitude": 91.7498,
            "created_at": now - timedelta(hours=2, minutes=40),
            "updated_at": now - timedelta(hours=2, minutes=40),
        },
        {
            "message": "Child with breathing difficulty needs urgent evacuation in Jaipur heatwave zone.",
            "phone": "+91 9899003310",
            "city": "Jaipur, Rajasthan",
            "priority": "high",
            "status": "acknowledged",
            "latitude": 26.9157,
            "longitude": 75.8011,
            "created_at": now - timedelta(hours=1, minutes=35),
            "updated_at": now - timedelta(hours=1),
        },
        {
            "message": "Pregnant woman needs transport from flooded lane near Patna embankment area.",
            "phone": "+91 9899003311",
            "city": "Patna, Bihar",
            "priority": "high",
            "status": "new",
            "latitude": 25.6080,
            "longitude": 85.1234,
            "created_at": now - timedelta(hours=3, minutes=25),
            "updated_at": now - timedelta(hours=3, minutes=25),
        },
        {
            "message": "Immediate food packets and clean water required near Bengaluru underpass shelters.",
            "phone": "+91 9899003312",
            "city": "Bengaluru, Karnataka",
            "priority": "medium",
            "status": "new",
            "latitude": 12.9155,
            "longitude": 77.6248,
            "created_at": now - timedelta(hours=2, minutes=15),
            "updated_at": now - timedelta(hours=2, minutes=15),
        },
        {
            "message": "Senior patient requires oxygen support in Srinagar snowbound neighborhood.",
            "phone": "+91 9899003313",
            "city": "Srinagar, Jammu and Kashmir",
            "priority": "high",
            "status": "acknowledged",
            "latitude": 34.0912,
            "longitude": 74.8046,
            "created_at": now - timedelta(hours=9, minutes=5),
            "updated_at": now - timedelta(hours=8, minutes=15),
        },
        {
            "message": "Requesting evacuation from inundated ground floor homes near Chennai Velachery.",
            "phone": "+91 9899003314",
            "city": "Chennai, Tamil Nadu",
            "priority": "high",
            "status": "new",
            "latitude": 12.9791,
            "longitude": 80.2194,
            "created_at": now - timedelta(hours=1, minutes=50),
            "updated_at": now - timedelta(hours=1, minutes=50),
        },
        {
            "message": "Need blankets and medicines for children near Port Blair storm shelter queue.",
            "phone": "+91 9899003315",
            "city": "Port Blair, Andaman and Nicobar Islands",
            "priority": "medium",
            "status": "handled",
            "latitude": 11.6254,
            "longitude": 92.7241,
            "created_at": now - timedelta(hours=12, minutes=10),
            "updated_at": now - timedelta(hours=10, minutes=45),
        },
        {
            "message": "Two workers trapped after warehouse fire spread in Ahmedabad industrial block.",
            "phone": "+91 9899003316",
            "city": "Ahmedabad, Gujarat",
            "priority": "high",
            "status": "acknowledged",
            "latitude": 23.0347,
            "longitude": 72.6221,
            "created_at": now - timedelta(hours=1, minutes=10),
            "updated_at": now - timedelta(minutes=40),
        },
        {
            "message": "Need emergency medical team near Kochi hillside settlement after landslip.",
            "phone": "+91 9899003317",
            "city": "Kochi, Kerala",
            "priority": "medium",
            "status": "new",
            "latitude": 9.9361,
            "longitude": 76.2608,
            "created_at": now - timedelta(hours=4, minutes=20),
            "updated_at": now - timedelta(hours=4, minutes=20),
        },
        {
            "message": "Requesting road clearing and ambulance access near Dehradun cloudburst area.",
            "phone": "+91 9899003318",
            "city": "Dehradun, Uttarakhand",
            "priority": "high",
            "status": "new",
            "latitude": 30.3202,
            "longitude": 78.0351,
            "created_at": now - timedelta(hours=5, minutes=5),
            "updated_at": now - timedelta(hours=5, minutes=5),
        },
        {
            "message": "People stranded without ferry access near Agartala connector bridge damage.",
            "phone": "+91 9899003319",
            "city": "Agartala, Tripura",
            "priority": "medium",
            "status": "handled",
            "latitude": 23.8349,
            "longitude": 91.2817,
            "created_at": now - timedelta(hours=7, minutes=15),
            "updated_at": now - timedelta(hours=6, minutes=5),
        },
        {
            "message": "Urgent drinking water required for island homes affected in Kavaratti lagoon flooding.",
            "phone": "+91 9899003320",
            "city": "Kavaratti, Lakshadweep",
            "priority": "high",
            "status": "new",
            "latitude": 10.5709,
            "longitude": 72.6374,
            "created_at": now - timedelta(hours=13, minutes=30),
            "updated_at": now - timedelta(hours=13, minutes=30),
        },
    ])

    for sample in incidents:
        if not Incident.query.filter_by(title=sample["title"]).first():
            db.session.add(Incident(user_id=demo_user.id, **sample))

    for sample in shelters:
        if not Shelter.query.filter_by(name=sample["name"]).first():
            db.session.add(
                Shelter(
                    name=sample["name"],
                    city=sample["city"],
                    address=sample["address"],
                    latitude=sample["latitude"],
                    longitude=sample["longitude"],
                    capacity=sample["capacity"],
                    occupied=sample["occupied"],
                    contact=sample["contact"],
                    facilities=json.dumps(sample["facilities"]),
                    status=sample["status"],
                    created_at=now,
                    updated_at=now,
                )
            )

    for sample in relief_centers:
        if not Relief.query.filter_by(name=sample["name"]).first():
            db.session.add(
                Relief(
                    title=sample["name"],
                    description=f"{sample['type']} serving {sample['city']}",
                    name=sample["name"],
                    type=sample["type"],
                    city=sample["city"],
                    address=sample["address"],
                    contact=sample["contact"],
                    latitude=sample["latitude"],
                    longitude=sample["longitude"],
                    supplies=json.dumps(sample["supplies"]),
                    status=sample["status"],
                    posted_by=demo_user.id,
                    created_at=sample["created_at"],
                    updated_at=sample["updated_at"],
                )
            )

    for sample in sos_entries:
        if not SOS.query.filter_by(message=sample["message"]).first():
            db.session.add(SOS(user_id=demo_user.id, **sample))

    db.session.commit()
