USE disaster_management;

-- Sample Users
INSERT INTO users (name, email, password_hash, role) VALUES
('Admin One', 'admin@example.com', '$pbkdf2-sha256$29000$hashhere', 'admin'),
('John Doe', 'john@example.com', '$pbkdf2-sha256$29000$hashhere', 'user'),
('Jane Smith', 'jane@example.com', '$pbkdf2-sha256$29000$hashhere', 'user');

-- (⚠️ Replace $pbkdf2-sha256$hashhere with actual password hashes generated by Flask, 
-- e.g. using werkzeug.security.generate_password_hash("password"))

-- Sample Shelters
INSERT INTO shelters (name, latitude, longitude, capacity, contact) VALUES
('Community Hall A', 28.7041, 77.1025, 200, '9876543210'),
('School Building B', 19.0760, 72.8777, 150, '9123456780'),
('Town Hall C', 13.0827, 80.2707, 300, '9988776655');

-- Sample Incidents
INSERT INTO incidents (user_id, title, description, latitude, longitude, status) VALUES
(2, 'Flooded Area', 'Severe waterlogging reported', 28.5355, 77.3910, 'reported'),
(3, 'Building Collapse', 'Collapsed building near market', 19.2183, 72.9781, 'verified');

-- Sample Relief Updates
INSERT INTO relief (title, description, latitude, longitude, posted_by) VALUES
('Food Distribution Camp', 'Free food available at Community Hall A', 28.7041, 77.1025, 1),
('Medical Aid', 'Doctors providing aid at School Building B', 19.0760, 72.8777, 1);

-- Sample SOS Requests
INSERT INTO sos (user_id, message, latitude, longitude, status) VALUES
(2, 'Trapped on rooftop, need urgent rescue!', 28.4595, 77.0266, 'new'),
(3, 'Family stranded, need medical help', 19.0760, 72.8777, 'acknowledged');
